language: node_js
cache:
  directories:
    - ~/.npm
notifications:
  email: false
node_js:
  - '12'
  - '10'
install:
  - npm install
script:
  - npm run test
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
